server:
  restart: always
  image: nginx:latest
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - web
  ports:
    - "8888:5000"

web:
  restart: always
  build: .
  working_dir: /var/www
  expose:
    - "5000"